task:
  datadir: "data"
  batch_size: 32
  num_workers: 4
model:
  vocab_size: 10000
  embedding_dim: 100
  hidden_size: 200
  nonlinearity: "relu"
  dropout: 0.1
  learn_rate: 1e-3
trainer:
  deterministic: true
  seed: 432

